# chiavi
sonar.organization=snakebyteteam
sonar.projectKey=SnakeByteTeam_MVP
sonar.projectName=MVP

# impostazioni
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**, **/*.spec.ts, dist/**, coverage/**

# definizione dei due moduli
sonar.modules=backend,frontend

# modulo backend
backend.sonar.projectName=Backend
backend.sonar.sources=src
backend.sonar.tests=src
backend.sonar.test.inclusions=**/*.spec.ts
backend.sonar.javascript.lcov.reportPaths=test/coverage/lcov.info

# modulo frontend
frontend.sonar.projectName=Frontend
frontend.sonar.sources=src
frontend.sonar.tests=src
frontend.sonar.test.inclusions=**/*.spec.ts
frontend.sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info