services: 
  database:
    image: timescale/timescaledb:latest-pg18
    container_name: postgres-timescale
    restart: unless-stopped
    environment: 
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBNAME}
    ports:
      - 127.0.0.1:5434:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    env_file: 
      - .env

  server: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend
    ports: 
      - 3000:3000
    volumes: 
      - ./src:/usr/src/app/src
    depends_on:
      - database
    env_file:
      - .env

volumes: 
  postgres_data: