import { INestApplication, ValidationPipe } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { Test, TestingModule } from '@nestjs/testing';
import { createHash } from 'node:crypto';
import * as http from 'node:http';
import cookieParser from 'cookie-parser';
import request from 'supertest';
import { AuthModule } from 'src/auth/auth.module';
import { DatabaseModule, PG_POOL } from 'src/database/database.module';
import { createMockPgPool, normalizeSql } from './helpers/mock-pg';

describe('Auth Integration Test', () => {
  let app: INestApplication;
  let jwtService: JwtService;

  const ACCESS_SECRET = 'integration-access-secret';
  const REFRESH_SECRET = 'integration-refresh-secret';

  const state = {
    users: [
      {
        id: 1,
        username: 'admin.user',
        roleName: 'Amministratore',
        first_access: false,
        password: '',
      },
      {
        id: 2,
        username: 'first.user',
        roleName: 'Amministratore',
        first_access: true,
        password: '',
      },
    ],
  };

  const hashPassword = (value: string) =>
    createHash('sha512').update(value).digest('hex');

  beforeEach(async () => {
    process.env.ACCESS_SECRET = ACCESS_SECRET;
    process.env.REFRESH_SECRET = REFRESH_SECRET;

    state.users[0].password = hashPassword('plain-password');
    state.users[0].first_access = false;
    state.users[1].password = hashPassword('temp-password');
    state.users[1].first_access = true;

    const pool = createMockPgPool(async (rawSql, params) => {
      const sql = normalizeSql(rawSql);

      if (
        sql.includes('from "user" u') &&
        sql.includes('join role r') &&
        sql.includes('where u.username = $1 and u.password = $2')
      ) {
        const [username, password] = params as [string, string];
        const user = state.users.find(
          (u) => u.username === username && u.password === password,
        );

        if (!user) {
          return { rows: [], rowCount: 0 };
        }

        return {
          rows: [
            {
              id: user.id,
              username: user.username,
              role:
                user.roleName === 'Amministratore'
                  ? 'AMMINISTRATORE'
                  : user.roleName,
              first_access: user.first_access,
            },
          ],
          rowCount: 1,
        };
      }

      if (
        sql.includes('update "user" set password = $1, first_access = $2 where username = $3')
      ) {
        const [newPassword, firstAccess, username] = params as [
          string,
          boolean,
          string,
        ];
        const user = state.users.find((u) => u.username === username);
        if (user) {
          user.password = newPassword;
          user.first_access = firstAccess;
        }

        return { rows: [], rowCount: user ? 1 : 0 };
      }

      throw new Error(`Unhandled SQL in auth integration test: ${sql}`);
    });

    const module: TestingModule = await Test.createTestingModule({
      imports: [DatabaseModule, AuthModule],
    })
      .overrideProvider(PG_POOL)
      .useValue(pool)
      .compile();

    app = module.createNestApplication();
    app.use(cookieParser());
    app.useGlobalPipes(
      new ValidationPipe({
        whitelist: true,
        forbidNonWhitelisted: true,
        transform: true,
      }),
    );
    await app.init();

    jwtService = new JwtService({ secret: ACCESS_SECRET });
  });

  afterEach(async () => {
    if (app) {
      await app.close();
    }
  });

  it('should login and set refresh cookie with real auth flow', async () => {
    const response = await request(app.getHttpServer() as http.Server)
      .post('/auth/login')
      .send({ username: 'admin.user', password: 'plain-password' })
      .expect(201);

    expect(response.body).toHaveProperty('accessToken');
    expect(response.headers['set-cookie']).toBeDefined();
  });

  it('should execute first-login end to end and persist credentials change', async () => {
    const firstAccessToken = jwtService.sign({
      id: 2,
      username: 'first.user',
      role: 'AMMINISTRATORE',
      firstAccess: true,
    });

    await request(app.getHttpServer() as http.Server)
      .post('/auth/first-login')
      .set('Authorization', `Bearer ${firstAccessToken}`)
      .send({
        username: 'first.user',
        password: 'new-password',
        tempPassword: 'temp-password',
      })
      .expect(201);

    expect(state.users[1].first_access).toBe(false);
    expect(state.users[1].password).toBe(hashPassword('new-password'));
  });

  it('should refresh token from cookie generated by /auth/login', async () => {
    const login = await request(app.getHttpServer() as http.Server)
      .post('/auth/login')
      .send({ username: 'admin.user', password: 'plain-password' })
      .expect(201);

    const refresh = await request(app.getHttpServer() as http.Server)
      .post('/auth/refresh')
      .set('Cookie', login.headers['set-cookie'])
      .expect(201);

    expect(refresh.body).toHaveProperty('accessToken');
  });

  it('should return 401 on /auth/refresh without cookie', async () => {
    await request(app.getHttpServer() as http.Server)
      .post('/auth/refresh')
      .expect(401);
  });
});
