export enum DeviceType {
  UNKNOWN = 'UNKNOWN',
  THERMOSTAT = 'THERMOSTAT',
  FALL_SENSOR = 'FALL_SENSOR',
  PRESENCE_SENSOR = 'PRESENCE_SENSOR',
  LIGHT = 'LIGHT',
  ALARM_BUTTON = 'ALARM_BUTTON',
  ENTRANCE_DOOR = 'ENTRANCE_DOOR',
  BLIND = 'BLIND',
}
