export enum AuthErrorType {
	USERNAME_OR_PASSWORD_WRONG = 'USERNAME_OR_PASSWORD_WRONG',
	USERNAME_OR_TEMP_PASSWORD_WRONG = 'USERNAME_OR_TEMP_PASSWORD_WRONG',
	NEW_PASSWORD_EQUALS_TEMP = 'NEW_PASSWORD_EQUALS_TEMP',
	NEW_PASSWORD_NOT_VALID = 'NEW_PASSWORD_NOT_VALID',
}
