events {
    worker_connections 1024;
}

http {
    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=api_cache:10m max_size=100m inactive=24h use_temp_path=off;

    map $time_iso8601 $today {
        default $time_iso8601;
    }

    server {
        listen 80;

        location /analytics/ {
            proxy_pass http://server:3000/analytics/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_cache api_cache;
            proxy_cache_key "$uri$is_args$args";
            proxy_cache_bypass $arg_refresh;
            proxy_cache_valid 200 24h;
            proxy_cache_use_stale error timeout updating;
            proxy_ignore_headers Cache-Control Expires Set-Cookie;

            add_header X-Cache-Status $upstream_cache_status;
        }

        location / {
            proxy_pass http://frontend:4200;
        }
    }
}